spring.application.name=backend

# Server
server.port=8080

# H2 in-memory database
spring.datasource.url=jdbc:h2:mem:pawfectdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none

# Run schema.sql and data.sql on startup
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
