DROP TABLE IF EXISTS pets;
DROP TABLE IF EXISTS petposts;

CREATE TABLE pets (
                      id INT PRIMARY KEY,
                      name VARCHAR(100),
                      species VARCHAR(50),
                      breed VARCHAR(100),
                      age INT
);

CREATE TABLE petposts (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          pet_name VARCHAR(100),
                          species VARCHAR(50),
                          breed VARCHAR(100),
                          age INT,
                          temperament VARCHAR(100),
                          description VARCHAR(500),
                          image_url VARCHAR(255),
                          provider_name VARCHAR(100)
);
